services:
  app:
    container_name: ielts-moc-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT:-4011}
    ports:
      - "${PORT:-4011}:${PORT:-4011}"
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
    networks:
      - default
      - ielts-net

networks:
  ielts-net:
    external: true
